IIF(TRANSACTION_NAME = 'DEALER SALES',
       IIF(PS_ACCOUNT_NUMBER = '110025' AND DIVISION_INDICATOR = 'T' AND INHOUSE_INDICATOR = 'N',GL_INVOICE_AMT,
       IIF(PS_ACCOUNT_NUMBER = '110030' AND DIVISION_INDICATOR = 'L' AND INHOUSE_INDICATOR = 'N' AND PIO_INDICATOR = 'N',GL_INVOICE_AMT-GL_PPO_PRICE_AMT,
       IIF(PS_ACCOUNT_NUMBER = '110030' AND DIVISION_INDICATOR = 'L' AND INHOUSE_INDICATOR = 'N' AND PIO_INDICATOR = 'Y',GL_PPO_PRICE_AMT,
       IIF(PS_ACCOUNT_NUMBER = '110130' AND DIVISION_INDICATOR = 'T' AND INHOUSE_INDICATOR = 'Y' AND PIO_INDICATOR = 'N',GL_INVOICE_AMT-GL_PPO_PRICE_AMT,
       IIF(PS_ACCOUNT_NUMBER = '110130' AND DIVISION_INDICATOR = 'T' AND INHOUSE_INDICATOR = 'Y' AND PIO_INDICATOR = 'Y',GL_PPO_PRICE_AMT,
       IIF(PS_ACCOUNT_NUMBER = '110140' AND DIVISION_INDICATOR = 'L' AND INHOUSE_INDICATOR = 'Y' AND PIO_INDICATOR = 'N',GL_INVOICE_AMT-GL_PPO_PRICE_AMT,
       IIF(PS_ACCOUNT_NUMBER = '110140' AND DIVISION_INDICATOR = 'L' AND INHOUSE_INDICATOR = 'Y' AND PIO_INDICATOR = 'Y',GL_PPO_PRICE_AMT,
       IIF(PS_ACCOUNT_NUMBER = '125000',GL_COST_OF_SALES_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '210020' AND DIVISION_INDICATOR = 'T',GL_DEALER_ADVERTISING_COST_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '210030' AND DIVISION_INDICATOR = 'L',GL_DEALER_ADVERTISING_COST_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '210120',GL_TOTAL_HB_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '210135' AND DIVISION_INDICATOR = 'T' AND PRICE_FIELD_INDICATOR = 'DAP',GL_TOTAL_DAP_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '210135' AND DIVISION_INDICATOR = 'L' AND PRICE_FIELD_INDICATOR = 'DAP',GL_TOTAL_DAP_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '210135' AND DIVISION_INDICATOR = 'L' AND PRICE_FIELD_INDICATOR = 'VDS',GL_TOTAL_LDS_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '210136' AND DIVISION_INDICATOR = 'L' AND PRICE_FIELD_INDICATOR = 'SE',GL_TOTAL_SE_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '210136' AND DIVISION_INDICATOR = 'L' AND PRICE_FIELD_INDICATOR = 'LDMC',GL_TOTAL_LDMC_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '210136' AND DIVISION_INDICATOR = 'L' AND PRICE_FIELD_INDICATOR = 'VTS',GL_TOTAL_LTS_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '210150' AND DIVISION_INDICATOR = 'T',GL_TOTAL_WFR_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '210160' AND DIVISION_INDICATOR = 'L',GL_TOTAL_WFR_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '220055' AND DIVISION_INDICATOR = 'L',GL_GAS_GUZZLER_TAX_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '400000',GL_SALE_PRICE_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '410610',GL_FLEET_DISCOUNT_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '410810' AND DIVISION_INDICATOR = 'T',(GL_COMPANY_CAR_DISCOUNT_AMT+GL_NON_PIO_ITEMS_PRICE_AMT)*-1,
       IIF(PS_ACCOUNT_NUMBER = '410830',GL_GAS_PRICE_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '410910',GL_DEST_PROCESS_HANDLING_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '412040' AND DIVISION_INDICATOR = 'L',(GL_COMPANY_CAR_DISCOUNT_AMT+GL_NON_PIO_ITEMS_PRICE_AMT)*-1,
       IIF(PS_ACCOUNT_NUMBER = '421010' AND DIVISION_INDICATOR = 'T',GL_PPO_PRICE_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '422000' AND DIVISION_INDICATOR = 'L',GL_PPO_PRICE_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '500000',GL_COST_OF_SALES_AMT))))))))))))))))))))))))))))))
			  
IIF(TRANSACTION_NAME = 'DISTRIBUTOR SALES',
       IIF(PS_ACCOUNT_NUMBER = '110010',GL_INVOICE_AMT,
       IIF(PS_ACCOUNT_NUMBER = '120000' AND TRANSACTION_CODE ='PDR',(GL_CIF_COST_AMT+GL_FAST_FSA_COST_AMT+GL_FAST_PIO_COST_AMT)*-1,
       IIF(PS_ACCOUNT_NUMBER = '120120' AND (TRANSACTION_CODE ='PDRB' OR TRANSACTION_CODE = 'PDCR'),GL_COST_OF_SALES_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '210270' AND TRANSACTION_CODE ='PDR',GL_PORT_CHARGE_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '220205' AND TRANSACTION_CODE ='PDR',GL_DUTY_COST_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '220220' AND TRANSACTION_CODE ='PDR',GL_WHARFAGE_HANDLING_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '400000',GL_SALE_PRICE_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '410610',GL_PRICE_PROTECTION_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '410910',GL_INLAND_FREIGHT_CHARGE_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '500000',GL_COST_OF_SALES_AMT,
       IIF(PS_ACCOUNT_NUMBER = '521010' AND TRANSACTION_CODE ='PDR',GL_FAST_PIO_COST_AMT))))))))))))
			  
IIF(TRANSACTION_NAME = 'EXPORT SALES',
       IIF(PS_ACCOUNT_NUMBER = '110020' AND IN(COUNTRY_CODE,'465','801','809')=0,GL_INVOICE_AMT,
       IIF(PS_ACCOUNT_NUMBER = '125010' AND IN(COUNTRY_CODE,'465','801','809')=0,GL_COST_OF_SALES_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '220190',0,
       IIF(PS_ACCOUNT_NUMBER = '220360',0,   
       IIF(PS_ACCOUNT_NUMBER = '220370' AND IN(COUNTRY_CODE,'465','801','809')=0,GL_EXP_RAPGUARD_COST_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '220380' AND IN(COUNTRY_CODE,'465','801','809')=0,GL_EXP_OCEAN_FREIGHT_COST_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '220385' AND IN(COUNTRY_CODE,'465','801','809')=0 AND PRICE_FIELD_INDICATOR='BANK',GL_EXP_BANK_CHARGE_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '220385' AND IN(COUNTRY_CODE,'465','801','809')=0 AND PRICE_FIELD_INDICATOR='ENV',0,
       IIF(PS_ACCOUNT_NUMBER = '220385' AND IN(COUNTRY_CODE,'465','801','809')=0 AND PRICE_FIELD_INDICATOR='PRTSV',GL_EXP_PORT_SERVICE_CHARGE_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '299400',0,
       IIF(PS_ACCOUNT_NUMBER = '400000' AND IN(COUNTRY_CODE,'465','801','809')=0,GL_SALE_PRICE_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '421010' AND IN(COUNTRY_CODE,'465','801','809')=0,GL_PPO_PRICE_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '500000' AND IN(COUNTRY_CODE,'465','801','809')=0,GL_COST_OF_SALES_AMT,
       IIF(PS_ACCOUNT_NUMBER = '503010' AND IN(COUNTRY_CODE,'465','801','809')=0 AND PRICE_FIELD_INDICATOR='POE',GL_EXP_PORT_CHARGE_AMT,
       IIF(PS_ACCOUNT_NUMBER = '503010' AND IN(COUNTRY_CODE,'465','801','809')=0 AND PRICE_FIELD_INDICATOR='BANK',GL_EXP_BANK_CHARGE_AMT,
       IIF(PS_ACCOUNT_NUMBER = '503020',0,
       IIF(PS_ACCOUNT_NUMBER = '503030' AND IN(COUNTRY_CODE,'465','801','809')=0,GL_EXP_OCEAN_FREIGHT_COST_AMT,
       IIF(PS_ACCOUNT_NUMBER = '503040' AND IN(COUNTRY_CODE,'465','801','809')=0,GL_EXP_INSURANCE_COST_AMT,
       IIF(PS_ACCOUNT_NUMBER = '503050' AND IN(COUNTRY_CODE,'465','801','809')=0,GL_EXP_PORT_SERVICE_CHARGE_AMT,
       IIF(PS_ACCOUNT_NUMBER = '503080' AND IN(COUNTRY_CODE,'465','801','809')=0,GL_EXP_RAPGUARD_COST_AMT,
       IIF(PS_ACCOUNT_NUMBER = '503090' AND PRICE_FIELD_INDICATOR='ENV',0,
       IIF(PS_ACCOUNT_NUMBER = '503100',0,
       IIF(PS_ACCOUNT_NUMBER = '653155' AND IN(COUNTRY_CODE,'465','801','809')=0,GL_EXP_FLEET_DISCOUNT_AMT*-1))))))))))))))))))))))))
	   
IIF(TRANSACTION_NAME = 'MEXICO SALES',
       IIF(PS_ACCOUNT_NUMBER = '112143' AND ACCOUNTING_SERIES_CODE != 'DJ' AND PRICE_FIELD_INDICATOR = 'MEX',GL_INVOICE_AMT,
       IIF(PS_ACCOUNT_NUMBER = '112145' AND ACCOUNTING_SERIES_CODE  = 'DJ' AND PRICE_FIELD_INDICATOR = 'MEX',GL_INVOICE_AMT,
       IIF(PS_ACCOUNT_NUMBER = '125205',GL_COST_OF_SALES_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '210270',GL_PORT_CHARGE_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '400000' AND PRICE_FIELD_INDICATOR = 'MEX',GL_SALE_PRICE_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '500000',GL_COST_OF_SALES_AMT+GL_PORT_CHARGE_AMT)))))))

IIF(TRANSACTION_NAME = 'PORT STOCK',
       IIF(PS_ACCOUNT_NUMBER = '125000',GL_COST_OF_SALES_AMT))
	   
IIF(TRANSACTION_NAME = 'CREDIT REBILL STOCK',
       IIF(PS_ACCOUNT_NUMBER = '120120' AND (TRANSACTION_CODE ='PDRB' OR TRANSACTION_CODE = 'PDCR'),GL_COST_OF_SALES_AMT))

IIF(TRANSACTION_NAME = 'EXPORT STOCK',
       IIF(PS_ACCOUNT_NUMBER = '125010' AND IN(COUNTRY_CODE,'465','801','809')=0,GL_COST_OF_SALES_AMT))

IIF(TRANSACTION_NAME = 'MEXICO STOCK',
       IIF(PS_ACCOUNT_NUMBER = '125205',GL_COST_OF_SALES_AMT))

	   
IIF(TRANSACTION_NAME = 'MEXICO PURCHASES',
       IIF(PS_ACCOUNT_NUMBER = '125205',GL_COST_OF_SALES_AMT,
       IIF(PS_ACCOUNT_NUMBER = '212000',GL_COST_OF_SALES_AMT*-1)))))))
	   
IIF(TRANSACTION_NAME = 'DEALER SALES UNITS',
       IIF(PS_ACCOUNT_NUMBER = '125000',QUANTITY*-1,
       IIF(PS_ACCOUNT_NUMBER = '229000',QUANTITY,
       IIF(PS_ACCOUNT_NUMBER = '400000',QUANTITY*-1,
       IIF(PS_ACCOUNT_NUMBER = '500000',QUANTITY)))))
	   
IIF(TRANSACTION_NAME = 'DISTRIBUTOR SALES UNITS',
       IIF(PS_ACCOUNT_NUMBER = '400000',QUANTITY*-1,
       IIF(PS_ACCOUNT_NUMBER = '500000',QUANTITY)))
	   
IIF(TRANSACTION_NAME = 'EXPORT SALES UNITS',
       IIF(PS_ACCOUNT_NUMBER = '400000',QUANTITY*-1,
       IIF(PS_ACCOUNT_NUMBER = '500000',QUANTITY)))
	   
IIF(TRANSACTION_NAME = 'RELEASES TO PORT STOCK',
       IIF(PS_ACCOUNT_NUMBER = '120000' AND DIVISION_INDICATOR='T',(GL_CIF_COST_AMT+GL_FAST_PIO_COST_AMT+GL_FAST_FSA_COST_AMT)*-1,
       IIF(PS_ACCOUNT_NUMBER = '121000' AND DIVISION_INDICATOR='L',(GL_CIF_COST_AMT+GL_FAST_PIO_COST_AMT+GL_FAST_FSA_COST_AMT)*-1,
       IIF(PS_ACCOUNT_NUMBER = '125000',GL_COST_OF_SALES_AMT,
       IIF(PS_ACCOUNT_NUMBER = '210270' AND DIVISION_INDICATOR='T',GL_PORT_CHARGE_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '210290' AND DIVISION_INDICATOR='L',GL_PORT_CHARGE_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '220205',GL_DUTY_COST_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '220220',GL_WHARFAGE_HANDLING_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '521010' AND DIVISION_INDICATOR='T',GL_FAST_PIO_COST_AMT,
       IIF(PS_ACCOUNT_NUMBER = '522000' AND DIVISION_INDICATOR='L',GL_FAST_PIO_COST_AMT))))))))))
	   
IIF(TRANSACTION_NAME = 'RELEASES TO EXPORT STOCK',
       IIF(PS_ACCOUNT_NUMBER = '120000',(GL_COST_OF_SALES_AMT+GL_PPO_FAST_COST_AMT)*-1,
       IIF(PS_ACCOUNT_NUMBER = '125010',GL_COST_OF_SALES_AMT,
       IIF(PS_ACCOUNT_NUMBER = '521010',GL_PPO_FAST_COST_AMT))))
	   
IIF(TRANSACTION_NAME = 'REGION REBILLS',
       IIF(PS_ACCOUNT_NUMBER = '120120',GL_COST_OF_SALES_AMT,
       IIF(PS_ACCOUNT_NUMBER = '125000',GL_COST_OF_SALES_AMT*-1)))
	   
IIF(TRANSACTION_NAME = 'REGION CREDITS',
       IIF(PS_ACCOUNT_NUMBER = '120120',GL_COST_OF_SALES_AMT,
       IIF(PS_ACCOUNT_NUMBER = '125000',GL_COST_OF_SALES_AMT*-1)))
	   
IIF(TRANSACTION_NAME = 'SAB104 DRAFTS' AND ACCOUNTING_MONTH = SAB104_MONTH AND AUTO_REVERSING_ENTRY_FLAG = 'N',
       IIF(PS_ACCOUNT_NUMBER = '110025' AND DIVISION_INDICATOR = 'T',GL_SAB104_SALE_PRICE_AMT,
       IIF(PS_ACCOUNT_NUMBER = '110030' AND DIVISION_INDICATOR = 'L',GL_SAB104_SALE_PRICE_AMT,
       IIF(PS_ACCOUNT_NUMBER = '125000',GL_COST_OF_SALES_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '400000',GL_SAB104_SALE_PRICE_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '500000',GL_COST_OF_SALES_AMT))))),
IIF(TRANSACTION_NAME = 'SAB104 DRAFTS' AND ACCOUNTING_MONTH != SAB104_MONTH AND AUTO_REVERSING_ENTRY_FLAG = 'Y',
       IIF(PS_ACCOUNT_NUMBER = '110025' AND DIVISION_INDICATOR = 'T',GL_SAB104_SALE_PRICE_AMT,
       IIF(PS_ACCOUNT_NUMBER = '110030' AND DIVISION_INDICATOR = 'L',GL_SAB104_SALE_PRICE_AMT,
       IIF(PS_ACCOUNT_NUMBER = '125000',GL_COST_OF_SALES_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '400000',GL_SAB104_SALE_PRICE_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '500000',GL_COST_OF_SALES_AMT)))))))
	   
IIF(TRANSACTION_NAME = 'TDPR CBU PURCHASES',
       IIF(PS_ACCOUNT_NUMBER = '120000',GL_CIF_COST_AMT,
       IIF(PS_ACCOUNT_NUMBER = '212000',GL_CIF_COST_AMT*-1)))
	   
IIF(TRANSACTION_NAME = 'TDPR CBU SALES',
       IIF(PS_ACCOUNT_NUMBER = '112180',GL_INVOICE_AMT,
       IIF(PS_ACCOUNT_NUMBER = '120000',GL_COST_OF_SALES_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '400000',GL_SALE_PRICE_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '500000',GL_COST_OF_SALES_AMT)))))
	   
IIF(TRANSACTION_NAME = 'CBU PURCHASES',
       IIF(PS_ACCOUNT_NUMBER = '120000' AND DIVISION_INDICATOR = 'T',GL_CIF_COST_AMT,
       IIF(PS_ACCOUNT_NUMBER = '121000' AND DIVISION_INDICATOR = 'L',GL_CIF_COST_AMT,
       IIF(PS_ACCOUNT_NUMBER = '212000',GL_CIF_COST_AMT*-1))))
	   
IIF(TRANSACTION_NAME = 'NAP PURCHASES',
       IIF(PS_ACCOUNT_NUMBER = '120000' AND DIVISION_INDICATOR = 'T',GL_MIT_AMT,
       IIF(PS_ACCOUNT_NUMBER = '121000' AND DIVISION_INDICATOR = 'L',GL_MIT_AMT,
       IIF(PS_ACCOUNT_NUMBER = '210220',GL_ACCOUNTS_PAYABLE_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '210230',GL_ACCOUNTS_PAYABLE_AMT*-1,
       IIF(PS_ACCOUNT_NUMBER = '210270' AND DIVISION_INDICATOR = 'T',GL_PORT_CHARGE_AMT,
       IIF(PS_ACCOUNT_NUMBER = '210290' AND DIVISION_INDICATOR = 'L',GL_PORT_CHARGE_AMT,
       IIF(PS_ACCOUNT_NUMBER = '220385' AND EXPORT_INDICATOR = 'Y',GL_PORT_CHARGE_AMT,
       IIF(PS_ACCOUNT_NUMBER = '500000',GL_COS_ADJUSTMENT_AMT,
       IIF(PS_ACCOUNT_NUMBER = '513025',GL_GAS_COST_AMT))))))))))

	   
