CREATE DATABASE Alfred;

USE Alfred;

CREATE TABLE AgeWeight (Age INT, Weight INT);

INSERT INTO AgeWeight VALUES (8,12);
INSERT INTO AgeWeight VALUES (4,5.5);
INSERT INTO AgeWeight VALUES (11,14);
INSERT INTO AgeWeight VALUES (4,5);
INSERT INTO AgeWeight VALUES (3,3.5);
INSERT INTO AgeWeight VALUES (6.5,7);
