IIF(TRANSACTION_TYPE_NAME_V = 'DEALER SALES',
       IIF(PS_ACCOUNT_NUMBER_V = '110025','ACCOUNT/NO INHOUSE',
       IIF(PS_ACCOUNT_NUMBER_V = '110030' AND PIO_INDICATOR_V = 'N','ACCOUNT/NO INHOUSE/NO PIO',
       IIF(PS_ACCOUNT_NUMBER_V = '110030' AND PIO_INDICATOR_V = 'Y','ACCOUNT/NO INHOUSE/PIO',
       IIF(PS_ACCOUNT_NUMBER_V = '110130' AND PIO_INDICATOR_V = 'N','ACCOUNT/VDS/SERIAL/INHOUSE/NO PIO',
       IIF(PS_ACCOUNT_NUMBER_V = '110130' AND PIO_INDICATOR_V = 'Y','ACCOUNT/SERIAL/INHOUSE/PIO',
       IIF(PS_ACCOUNT_NUMBER_V = '110140' AND PIO_INDICATOR_V = 'N','ACCOUNT/VDS/SERIAL/INHOUSE/NO PIO',
       IIF(PS_ACCOUNT_NUMBER_V = '110140' AND PIO_INDICATOR_V = 'Y','ACCOUNT/SERIAL/PORT/INHOUSE/PIO',
       IIF(PS_ACCOUNT_NUMBER_V = '125000','ACCOUNT/PRODUCT/REGION',
       IIF(PS_ACCOUNT_NUMBER_V = '210020','ACCOUNT/REGION',
       IIF(PS_ACCOUNT_NUMBER_V = '210030','ACCOUNT/REGION',
       IIF(PS_ACCOUNT_NUMBER_V = '210120','ACCOUNT/ALPHA/REGION',
       IIF(PS_ACCOUNT_NUMBER_V = '210135' AND DIVISION_NAME_V = 'TOYOTA', 'ACCOUNT/ALPHA/REGION',
       IIF(PS_ACCOUNT_NUMBER_V = '210135' AND DIVISION_NAME_V = 'LEXUS' AND INSTR(PS_INTERFACE_NAME,'CAP') != 0, 'ACCOUNT/ALPHA',
       IIF(PS_ACCOUNT_NUMBER_V = '210135' AND DIVISION_NAME_V = 'LEXUS' AND INSTR(PS_INTERFACE_NAME,'VDS') != 0, 'ACCOUNT/ALPHA',
       IIF(PS_ACCOUNT_NUMBER_V = '210136' AND DIVISION_NAME_V = 'LEXUS' AND INSTR(PS_INTERFACE_NAME,'SERV') !=0 , 'ACCOUNT/ALPHA',
       IIF(PS_ACCOUNT_NUMBER_V = '210136' AND DIVISION_NAME_V = 'LEXUS' AND INSTR(PS_INTERFACE_NAME,'LDMC') != 0, 'ACCOUNT/ALPHA',
       IIF(PS_ACCOUNT_NUMBER_V = '210136' AND DIVISION_NAME_V = 'LEXUS' AND INSTR(PS_INTERFACE_NAME,'VTS') != 0, 'ACCOUNT/ALPHA',
       IIF(PS_ACCOUNT_NUMBER_V = '210150','ACCOUNT/ALPHA/REGION',
       IIF(PS_ACCOUNT_NUMBER_V = '210160','ACCOUNT/ALPHA/REGION',
       IIF(PS_ACCOUNT_NUMBER_V = '220055','ACCOUNT/ALPHA/REGION',
       IIF(PS_ACCOUNT_NUMBER_V = '400000','ACCOUNT/ALPHA/REGION',
       IIF(PS_ACCOUNT_NUMBER_V = '410610','ACCOUNT/REGION',
       IIF(PS_ACCOUNT_NUMBER_V = '410810','ACCOUNT/REGION',
       IIF(PS_ACCOUNT_NUMBER_V = '410830','ACCOUNT/REGION',
       IIF(PS_ACCOUNT_NUMBER_V = '410910','ACCOUNT/PRODUCT/REGION',
       IIF(PS_ACCOUNT_NUMBER_V = '412040','ACCOUNT/REGION',
       IIF(PS_ACCOUNT_NUMBER_V = '421010','ACCOUNT/PORT',
       IIF(PS_ACCOUNT_NUMBER_V = '422000','ACCOUNT/PORT',
       IIF(PS_ACCOUNT_NUMBER_V = '500000','ACCOUNT/PRODUCT/REGION'))))))))))))))))))))))))))))),
IIF(TRANSACTION_TYPE_NAME_V = 'DISTRIBUTOR SALES',
       IIF(PS_ACCOUNT_NUMBER_V = '110010','ACCOUNT/REGION/REL-REB-CRE/INVOICE',
       IIF(PS_ACCOUNT_NUMBER_V = '120000','ACCOUNT/SHIP OIK',
       IIF(PS_ACCOUNT_NUMBER_V = '120120','ACCOUNT/REGION/REL-REB-CRE',
       IIF(PS_ACCOUNT_NUMBER_V = '210270','ACCOUNT/REGION/SHIP OIK',
       IIF(PS_ACCOUNT_NUMBER_V = '220205','ACCOUNT/SHIP OIK',
       IIF(PS_ACCOUNT_NUMBER_V = '220220','ACCOUNT/SHIP OIK',
       IIF(PS_ACCOUNT_NUMBER_V = '400000','ACCOUNT/PRODUCT/REGION/REL-REB-CRE',
       IIF(PS_ACCOUNT_NUMBER_V = '410610','ACCOUNT/REGION',
       IIF(PS_ACCOUNT_NUMBER_V = '410910','ACCOUNT/PRODUCT/REGION/REL-REB/CRE',
       IIF(PS_ACCOUNT_NUMBER_V = '500000','ACCOUNT/PRODUCT/REGION/REL-REB-CRE',
       IIF(PS_ACCOUNT_NUMBER_V = '521010','ACCOUNT'))))))))))),
IIF(TRANSACTION_TYPE_NAME_V = 'EXPORT SALES',
       IIF(PS_ACCOUNT_NUMBER_V = '110020','ACCOUNT/ALPHA/PLANT/INVOICE',
       IIF(PS_ACCOUNT_NUMBER_V = '125010','ACCOUNT/ALPHA/PLANT',
       IIF(PS_ACCOUNT_NUMBER_V = '220190','ACCOUNT/ALPHA/PLANT',
       IIF(PS_ACCOUNT_NUMBER_V = '220360','ACCOUNT/ALPHA/PLANT', 
       IIF(PS_ACCOUNT_NUMBER_V = '220370','ACCOUNT/ALPHA/PLANT',
       IIF(PS_ACCOUNT_NUMBER_V = '220380','ACCOUNT/ALPHA/PLANT',
       IIF(PS_ACCOUNT_NUMBER_V = '220385' AND INSTR(SUB_LEDGER_NUMBER,'BAN') != 0,'ACCOUNT/ALPHA/PLANT',
       IIF(PS_ACCOUNT_NUMBER_V = '220385' AND INSTR(SUB_LEDGER_NUMBER,'ENV') != 0,'ACCOUNT/ALPHA/PLANT',
       IIF(PS_ACCOUNT_NUMBER_V = '220385','ACCOUNT/ALPHA/PLANT',
       IIF(PS_ACCOUNT_NUMBER_V = '299400','ACCOUNT/ALPHA/PLANT',
       IIF(PS_ACCOUNT_NUMBER_V = '400000','ACCOUNT/PRODUCT/DEPT ID',
       IIF(PS_ACCOUNT_NUMBER_V = '400010','ACCOUNT/PRODUCT/DEPT ID',
       IIF(PS_ACCOUNT_NUMBER_V = '421010','ACCOUNT/PORT/DEPT ID',
       IIF(PS_ACCOUNT_NUMBER_V = '500000','ACCOUNT/PRODUCT/DEPT ID',
       IIF(PS_ACCOUNT_NUMBER_V = '503010' AND INSTR(SUB_LEDGER_NUMBER,'POE') != 0,'ACCOUNT/PRODUCT/DEPT ID',
       IIF(PS_ACCOUNT_NUMBER_V = '503010' AND INSTR(SUB_LEDGER_NUMBER,'BAN') != 0,'ACCOUNT/PRODUCT/DEPT ID',
       IIF(PS_ACCOUNT_NUMBER_V = '503020','ACCOUNT/PRODUCT/DEPT ID',
       IIF(PS_ACCOUNT_NUMBER_V = '503030','ACCOUNT/PRODUCT/DEPT ID',
       IIF(PS_ACCOUNT_NUMBER_V = '503040','ACCOUNT/PRODUCT/DEPT ID',
	   IIF(PS_ACCOUNT_NUMBER_V = '503050','ACCOUNT/PRODUCT/DEPT ID',
       IIF(PS_ACCOUNT_NUMBER_V = '503080','ACCOUNT/PRODUCT/DEPT ID',
       IIF(PS_ACCOUNT_NUMBER_V = '503090','ACCOUNT/PRODUCT/DEPT ID',
       IIF(PS_ACCOUNT_NUMBER_V = '503100','ACCOUNT/PRODUCT/DEPT ID',
       IIF(PS_ACCOUNT_NUMBER_V = '653155','ACCOUNT/PRODUCT/DEPT ID')))))))))))))))))))))))),
IIF(TRANSACTION_TYPE_NAME_V = 'MEXICO SALES',
       IIF(PS_ACCOUNT_NUMBER_V = '112143','ACCOUNT/PRODUCT/REGION/INVOICE',
       IIF(PS_ACCOUNT_NUMBER_V = '112145','ACCOUNT/PRODUCT/REGION/INVOICE',
       IIF(PS_ACCOUNT_NUMBER_V = '125205','ACCOUNT/PRODUCT/REGION/INVOICE',
       IIF(PS_ACCOUNT_NUMBER_V = '210270','ACCOUNT',
       IIF(PS_ACCOUNT_NUMBER_V = '400000','ACCOUNT/PRODUCT/REGION',
       IIF(PS_ACCOUNT_NUMBER_V = '500000','ACCOUNT/PRODUCT/REGION')))))),
IIF(TRANSACTION_TYPE_NAME_V = 'PORT STOCK',
       IIF(PS_ACCOUNT_NUMBER_V = '125000','ACCOUNT/PRODUCT/REGION'),
IIF(TRANSACTION_TYPE_NAME_V = 'CREDIT REBILL STOCK',
       IIF(PS_ACCOUNT_NUMBER_V = '120120','ACCOUNT/REGION/REL-REB-CRE'),
IIF(TRANSACTION_TYPE_NAME_V = 'EXPORT STOCK',
       IIF(PS_ACCOUNT_NUMBER_V = '125010','ACCOUNT/ALPHA/PLANT'),
IIF(TRANSACTION_TYPE_NAME_V = 'MEXICO STOCK',
       IIF(PS_ACCOUNT_NUMBER_V = '125205','ACCOUNT/PRODUCT/REGION/INVOICE'),
IIF(TRANSACTION_TYPE_NAME_V = 'MEXICO PURCHASES',
       IIF(PS_ACCOUNT_NUMBER_V = '125205','ACCOUNT/PRODUCT/REGION',
       IIF(PS_ACCOUNT_NUMBER_V = '212000','ACCOUNT/PLANT')),
IIF(TRANSACTION_TYPE_NAME_V = 'DEALER SALES UNITS',
       IIF(PS_ACCOUNT_NUMBER_V = '125000','ACCOUNT/ALPHA/REGION',
       IIF(PS_ACCOUNT_NUMBER_V = '229000','ACCOUNT',
       IIF(PS_ACCOUNT_NUMBER_V = '400000','ACCOUNT/ALPHA/REGION',
       IIF(PS_ACCOUNT_NUMBER_V = '500000','ACCOUNT/ALPHA/REGION')))),
IIF(TRANSACTION_TYPE_NAME_V = 'DISTRIBUTOR SALES UNITS',
       IIF(PS_ACCOUNT_NUMBER_V = '400000','ACCOUNT/ALPHA/REGION',
       IIF(PS_ACCOUNT_NUMBER_V = '500000','ACCOUNT/ALPHA/REGION')),
IIF(TRANSACTION_TYPE_NAME_V = 'EXPORT SALES UNITS',
       IIF(PS_ACCOUNT_NUMBER_V = '400000','ACCOUNT/ALPHA/PLANT/DEPT ID',
       IIF(PS_ACCOUNT_NUMBER_V = '500000','ACCOUNT/ALPHA/PLANT/DEPT ID')),
IIF(TRANSACTION_TYPE_NAME_V = 'RELEASES TO PORT STOCK',
       IIF(PS_ACCOUNT_NUMBER_V = '120000','ACCOUNT/SHIP OIK',
       IIF(PS_ACCOUNT_NUMBER_V = '121000','ACCOUNT/SHIP OIK',
       IIF(PS_ACCOUNT_NUMBER_V = '125000','ACCOUNT/PRODUCT/REGION',
       IIF(PS_ACCOUNT_NUMBER_V = '210270','ACCOUNT/SHIP OIK',
       IIF(PS_ACCOUNT_NUMBER_V = '210290','ACCOUNT/SHIP OIK',
       IIF(PS_ACCOUNT_NUMBER_V = '220205','ACCOUNT/DIVISION/SHIP OIK',
       IIF(PS_ACCOUNT_NUMBER_V = '220220','ACCOUNT/SHIP OIK',
       IIF(PS_ACCOUNT_NUMBER_V = '521010','ACCOUNT',
       IIF(PS_ACCOUNT_NUMBER_V = '522000','ACCOUNT'))))))))),
IIF(TRANSACTION_TYPE_NAME_V = 'RELEASES TO EXPORT STOCK',
       IIF(PS_ACCOUNT_NUMBER_V = '120000','ACCOUNT/SHIP OIK',
       IIF(PS_ACCOUNT_NUMBER_V = '125010','ACCOUNT/ALPHA/PLANT',
       IIF(PS_ACCOUNT_NUMBER_V = '521010','ACCOUNT'))),
IIF(TRANSACTION_TYPE_NAME_V = 'REGION REBILLS',
       IIF(PS_ACCOUNT_NUMBER_V = '120120','ACCOUNT/REGION',
       IIF(PS_ACCOUNT_NUMBER_V = '125000','ACCOUNT/PRODUCT/REGION')),
IIF(TRANSACTION_TYPE_NAME_V = 'REGION CREDITS',
       IIF(PS_ACCOUNT_NUMBER_V = '120120','ACCOUNT/REGION',
       IIF(PS_ACCOUNT_NUMBER_V = '125000','ACCOUNT/PRODUCT/REGION')),
IIF(TRANSACTION_TYPE_NAME_V = 'SAB104 DRAFTS' AND AUTO_REVERSING_ENTRY_FLAG = 'N',
       IIF(PS_ACCOUNT_NUMBER_V = '110025','ACCOUNT',
       IIF(PS_ACCOUNT_NUMBER_V = '110030','ACCOUNT',
       IIF(PS_ACCOUNT_NUMBER_V = '125000','ACCOUNT/BRAND',
       IIF(PS_ACCOUNT_NUMBER_V = '400000','ACCOUNT/PRODUCT/DEPT ID',
	   IIF(PS_ACCOUNT_NUMBER_V = '500000','ACCOUNT/PRODUCT/DEPT ID'))))),
IIF(TRANSACTION_TYPE_NAME_V = 'SAB104 DRAFTS' AND AUTO_REVERSING_ENTRY_FLAG = 'Y',
       IIF(PS_ACCOUNT_NUMBER_V = '110025','ACCOUNT',
       IIF(PS_ACCOUNT_NUMBER_V = '110030','ACCOUNT',
       IIF(PS_ACCOUNT_NUMBER_V = '125000','ACCOUNT/BRAND',
       IIF(PS_ACCOUNT_NUMBER_V = '400000','ACCOUNT/PRODUCT/DEPT ID',
	   IIF(PS_ACCOUNT_NUMBER_V = '500000','ACCOUNT/PRODUCT/DEPT ID'))))),
IIF(TRANSACTION_TYPE_NAME_V = 'TDPR CBU PURCHASES',
       IIF(PS_ACCOUNT_NUMBER_V = '120000','ACCOUNT',
       IIF(PS_ACCOUNT_NUMBER_V = '212000','ACCOUNT')),
IIF(TRANSACTION_TYPE_NAME_V = 'TDPR CBU SALES',
       IIF(PS_ACCOUNT_NUMBER_V = '112180','ACCOUNT',
       IIF(PS_ACCOUNT_NUMBER_V = '120000','ACCOUNT',
       IIF(PS_ACCOUNT_NUMBER_V = '400000','ACCOUNT/PRODUCT/REGION',
	   IIF(PS_ACCOUNT_NUMBER_V = '500000','ACCOUNT/PRODUCT/REGION')))),
IIF(TRANSACTION_TYPE_NAME_V = 'CBU PURCHASES',
       IIF(PS_ACCOUNT_NUMBER_V = '120000','ACCOUNT/SHIP',                                  --TOYOTA
       IIF(PS_ACCOUNT_NUMBER_V = '121000','ACCOUNT/SHIP',                                  --LEXUS
	   IIF(PS_ACCOUNT_NUMBER_V = '212000','ACCOUNT/DIVISION'))),                           --TMC PAYMENT
IIF(TRANSACTION_TYPE_NAME_V = 'NAP PURCHASES',
       IIF(PS_ACCOUNT_NUMBER_V = '120000','ACCOUNT/SHIP/ALPHA',                            --TOYOTA
       IIF(PS_ACCOUNT_NUMBER_V = '121000','ACCOUNT/SHIP/ALPHA',                            --LEXUS
	   IIF(PS_ACCOUNT_NUMBER_V = '210220','ACCOUNT/PLANT',                                 --POE    AND PORT IN ('C)
	   IIF(PS_ACCOUNT_NUMBER_V = '210230','ACCOUNT/PLANT',                                 --POE    AND PORT IN ()
	   IIF(PS_ACCOUNT_NUMBER_V = '210270','ACCOUNT/PLANT',                                 --POE    
	   IIF(PS_ACCOUNT_NUMBER_V = '210290','ACCOUNT/PLANT',                                 --LEXUS POE
	   IIF(PS_ACCOUNT_NUMBER_V = '220385','ACCOUNT/PLANT',                                 --EXPORT POE
	   IIF(PS_ACCOUNT_NUMBER_V = '500000','ACCOUNT/PRODUCT/REGION',                        --PRICE VAR
       IIF(PS_ACCOUNT_NUMBER_V = '513025','ACCOUNT/DIVISION/PORT'))))))))),                --GAS
IIF(INSTR(TRANSACTION_TYPE_NAME_V,'LND')!=0,
       IIF(PS_ACCOUNT_NUMBER_V = '210220','ACCOUNT/REGION/PORT/BRAND',                     --TLS    AND PORT IN ('GT','PR')
       IIF(PS_ACCOUNT_NUMBER_V = '210260','ACCOUNT/REGION/PORT/BRAND',                     --TOYOTA AND PORT IN ('BC')
       IIF(PS_ACCOUNT_NUMBER_V = '210270','ACCOUNT/REGION/PORT/SHIP'))),                   --TOYOTA AND PORT IN ('BC','PR','GT','TP')
IIF(INSTR(TRANSACTION_TYPE_NAME_V,'FPM')!=0,
       IIF(PS_ACCOUNT_NUMBER_V = '112300','ACCOUNT/REGION/PORT',                           --TLS    AND PORT IN ('GT','PR','SA')
       IIF(PS_ACCOUNT_NUMBER_V = '112320','ACCOUNT/REGION/PORT',                           --TMS    AND PORT IN ('GT','PR','SA')
       IIF(PS_ACCOUNT_NUMBER_V = '210260','ACCOUNT/REGION/PORT',                           --TOYOTA AND PORT IN ('BC')
       IIF(PS_ACCOUNT_NUMBER_V = '210270' AND DEBIT_AMT !=0,'ACCOUNT/REGION/PORT/SHIP',    --TOYOTA AND PORT IN ('BC','GT','PR','SA','TP')
       IIF(PS_ACCOUNT_NUMBER_V = '210270' AND CREDIT_AMT !=0,'ACCOUNT/REGION/PORT/SHIP',   --TOYOTA AND PORT IN ('TP')
	   IIF(PS_ACCOUNT_NUMBER_V = '220385' AND DEBIT_AMT !=0,'ACCOUNT/REGION/PORT/SHIP',    --EXPORT AND PORT IN ('BC','GT','PR','SA','TP')
	   IIF(PS_ACCOUNT_NUMBER_V = '220385' AND CREDIT_AMT !=0,'ACCOUNT/REGION/PORT/SHIP',   --EXPORT AND PORT IN ('TP')
       IIF(PS_ACCOUNT_NUMBER_V = '460040','ACCOUNT/REGION/PORT',                           --TLS    AND PORT IN PORT IN ('GT','PR')!=0
	   IIF(PS_ACCOUNT_NUMBER_V = '602045','ACCOUNT/REGION/PORT'))))))))),                          
IIF(INSTR(TRANSACTION_TYPE_NAME_V,'FPQ')!=0,
       IIF(PS_ACCOUNT_NUMBER_V = '112300','ACCOUNT/REGION/PORT',                           --TLS    AND PORT IN ('GT','LF','PR','SA')
       IIF(PS_ACCOUNT_NUMBER_V = '112320','ACCOUNT/REGION/PORT',                           --TMS    AND PORT IN ('GT','LF','PR','SA')
       IIF(PS_ACCOUNT_NUMBER_V = '210260','ACCOUNT/REGION/PORT',                           --TOYOTA AND PORT IN ('BC')
       IIF(PS_ACCOUNT_NUMBER_V = '210270' AND DEBIT_AMT !=0,'ACCOUNT/REGION/PORT/SHIP',    --TOYOTA AND PORT IN ('BC','CM','GT','LF','PR','SA','TP','WS')
       IIF(PS_ACCOUNT_NUMBER_V = '210270' AND CREDIT_AMT !=0,'ACCOUNT/REGION/PORT/SHIP',   --TOYOTA AND PORT IN ('CM','TP','WS')
	   IIF(PS_ACCOUNT_NUMBER_V = '220385' AND DEBIT_AMT !=0,'ACCOUNT/REGION/PORT/SHIP',    --EXPORT AND PORT IN ('BC','CM','GT','PR','SA','WS')
	   IIF(PS_ACCOUNT_NUMBER_V = '220385' AND CREDIT_AMT !=0,'ACCOUNT/REGION/PORT/SHIP',   --EXPORT AND PORT IN ('CM','WS')
       IIF(PS_ACCOUNT_NUMBER_V = '460040','ACCOUNT/REGION/PORT',                           --TLS    AND PORT IN ('GT','LF','PR','SA')
	   IIF(PS_ACCOUNT_NUMBER_V = '602045','ACCOUNT/REGION/PORT'))))))))),                         
IIF(INSTR(TRANSACTION_TYPE_NAME_V,'FQA')!=0,
       IIF(PS_ACCOUNT_NUMBER_V = '112300','ACCOUNT/REGION/PORT',                           --TLS    AND PORT IN ('GT','LA','LF','NY','PR','PT','SA')
       IIF(PS_ACCOUNT_NUMBER_V = '112320','ACCOUNT/REGION/PORT',                           --TMS    AND PORT IN ('GT','LA','LF','NY','PR','PT','SA')
       IIF(PS_ACCOUNT_NUMBER_V = '210220','ACCOUNT/REGION/PORT',                           --TOYOTA AND PORT IN ('JX')
       IIF(PS_ACCOUNT_NUMBER_V = '210260','ACCOUNT/REGION/PORT',                           --TOYOTA AND PORT IN ('BC','CM','SF')
       IIF(PS_ACCOUNT_NUMBER_V = '210270' AND DEBIT_AMT !=0,'ACCOUNT/REGION/PORT/SHIP',    --TOYOTA AND PORT IN ('BC','CM','GT','LA','LF','NY','PR','PT','SA','SF','TP','WS')
       IIF(PS_ACCOUNT_NUMBER_V = '210270' AND CREDIT_AMT !=0,'ACCOUNT/REGION/PORT/SHIP',   --TOYOTA AND PORT IN ('CM','TP','WS')
       IIF(PS_ACCOUNT_NUMBER_V = '210290' AND DEBIT_AMT !=0,'ACCOUNT/REGION/PORT/SHIP',    --LEXUS  AND PORT IN ('CM','JX','LA','NY','PT')
       IIF(PS_ACCOUNT_NUMBER_V = '210290' AND CREDIT_AMT !=0,'ACCOUNT/REGION/PORT/SHIP',   --LEXUS  AND PORT IN ('CM')
       IIF(PS_ACCOUNT_NUMBER_V = '220385' AND DEBIT_AMT !=0,'ACCOUNT/REGION/PORT/SHIP',    --EXPORT AND PORT IN ('GT','PR','SA','TP')
       IIF(PS_ACCOUNT_NUMBER_V = '220385' AND CREDIT_AMT !=0,'ACCOUNT/REGION/PORT/SHIP',   --EXPORT AND PORT IN ('TP')
       IIF(PS_ACCOUNT_NUMBER_V = '460040','ACCOUNT/REGION/PORT',                           --TLS    AND PORT IN ('GT','LA','LF','NY','PR','PT','SA')
       IIF(PS_ACCOUNT_NUMBER_V = '513000','ACCOUNT/REGION/PORT',                           --TLS    AND PORT IN ('CM')
       IIF(PS_ACCOUNT_NUMBER_V = '602045','ACCOUNT/REGION/PORT'))))))))))))),              --SUSP   AND PORT ALL 
IIF(INSTR(TRANSACTION_TYPE_NAME_V,'LQA')!=0,
       IIF(PS_ACCOUNT_NUMBER_V = '112300','ACCOUNT/REGION/PORT',                           --TLS    AND PORT IN ('GT','LA','LF','NY','PR','PT','SA')
       IIF(PS_ACCOUNT_NUMBER_V = '112320','ACCOUNT/REGION/PORT',                           --TMS    AND PORT IN ('GT','LA','LF','NY','PR','PT','SA')
       IIF(PS_ACCOUNT_NUMBER_V = '210220','ACCOUNT/REGION/PORT',                           --TOYOTA AND PORT IN ('JX')
       IIF(PS_ACCOUNT_NUMBER_V = '210260','ACCOUNT/REGION/PORT',                           --TOYOTA AND PORT IN ('BC','SF')
       IIF(PS_ACCOUNT_NUMBER_V = '460040','ACCOUNT/REGION/PORT',                           --TLS    AND PORT IN ('GT','LA','LF','NY','PR','PT','SA')
       IIF(PS_ACCOUNT_NUMBER_V = '500000','ACCOUNT/REGION/PORT/PRODUCT',                   --TMS    AND PORT IN ('BC','GT','JX','LA','LF','NY','PR','PT','SA','SF')
       IIF(PS_ACCOUNT_NUMBER_V = '513000','ACCOUNT/REGION/PORT',                           --TMS    AND PORT IN ('JX','LA','PT','SF')
	   IIF(PS_ACCOUNT_NUMBER_V = '602045','ACCOUNT/REGION/PORT')))))))),                   --TMS    AND PORT IN ('LA','NY')
IIF(INSTR(TRANSACTION_TYPE_NAME_V,'TPQA')!=0 AND INSTR(TRANSACTION_TYPE_NAME_V,'FSA') !=0,
       IIF(PS_ACCOUNT_NUMBER_V = '112300','ACCOUNT/REGION/PORT',                           --TLS    AND PORT IN ('GT','LA','LF','NY','PR','PT','SA')
       IIF(PS_ACCOUNT_NUMBER_V = '112320','ACCOUNT/REGION/PORT',                           --TMS    AND PORT IN ('GT','LA','LF','NY','PR','PT','SA')
       IIF(PS_ACCOUNT_NUMBER_V = '135100','ACCOUNT/REGION/PORT',                           --TMS    AND PORT IN ('GT','LA','LF','NY','PR','PT','SA')
       IIF(PS_ACCOUNT_NUMBER_V = '210220','ACCOUNT/REGION/PORT',                           --TMS    AND PORT IN ('JX')
       IIF(PS_ACCOUNT_NUMBER_V = '210230','ACCOUNT/REGION/PORT',                           --TMS    AND PORT IN ('TP')
       IIF(PS_ACCOUNT_NUMBER_V = '210260','ACCOUNT/REGION/PORT',                           --TMS    AND PORT IN ('CM','SF','WS')
       IIF(PS_ACCOUNT_NUMBER_V = '460000','ACCOUNT/REGION/PORT',                           --TLS    AND PORT IN ('GT','LA','LF','NY','PR','PT','SA')
       IIF(PS_ACCOUNT_NUMBER_V = '500000','ACCOUNT/REGION/PORT/PRODUCT',                   --TMS    AND PORT IN ('CM','GT','JX','LA','LF','NY','PR','PT','SA','SF','TP')
       IIF(PS_ACCOUNT_NUMBER_V = '513000','ACCOUNT/REGION/PORT',                           --TMS    AND PORT IN ('CM','GT','JX','LA','LF','NY','PR','PT','SA','SF','TP')
       IIF(PS_ACCOUNT_NUMBER_V = '521010','ACCOUNT/REGION/PORT',                           --TMS    AND PORT IN ('CM','GT','JX','LA','LF','NY','PR','PT','SA','SF','TP')
       IIF(PS_ACCOUNT_NUMBER_V = '522000','ACCOUNT/REGION/PORT',                           --TMS    AND PORT IN ('CM','GT','JX','LA','LF','NY','PR','PT','SA','SF','TP')
	   IIF(PS_ACCOUNT_NUMBER_V = '602045','ACCOUNT/REGION/PORT')))))))))))),
IIF(INSTR(TRANSACTION_TYPE_NAME_V,'TPQA')!=0 AND INSTR(TRANSACTION_TYPE_NAME_V,'PIO') !=0,
       IIF(PS_ACCOUNT_NUMBER_V = '112300','ACCOUNT/REGION/PORT',                           --TLS    AND PORT IN ('GT','LA','NY','PR','PT','SA')
       IIF(PS_ACCOUNT_NUMBER_V = '112320','ACCOUNT/REGION/PORT',                           --TMS    AND PORT IN ('GT','LA','NY','PR','PT','SA')
       IIF(PS_ACCOUNT_NUMBER_V = '210220','ACCOUNT/REGION/PORT',                           --TMS    AND PORT IN ('JX')
       IIF(PS_ACCOUNT_NUMBER_V = '210230','ACCOUNT/REGION/PORT',                           --TMS    AND PORT IN ('TP')
       IIF(PS_ACCOUNT_NUMBER_V = '210260','ACCOUNT/REGION/PORT',                           --TMS    AND PORT IN ('BC','CM','SF','WS')
       IIF(PS_ACCOUNT_NUMBER_V = '460000','ACCOUNT/REGION/PORT',                           --TMS    AND PORT IN ('GT','LA','NY','PR','PT','SA')
       IIF(PS_ACCOUNT_NUMBER_V = '521020','ACCOUNT/REGION/PORT',                           --TOYOTA AND PORT ALL
       IIF(PS_ACCOUNT_NUMBER_V = '522500','ACCOUNT/REGION/PORT',                           --LEXUS  AND PORT ALL
	   IIF(PS_ACCOUNT_NUMBER_V = '602045','ACCOUNT/REGION/PORT'))))))))),                   
IIF(INSTR(TRANSACTION_TYPE_NAME_V,'RP1')!=0,
       IIF(PS_ACCOUNT_NUMBER_V = '112300','ACCOUNT/REGION/PORT',                           --TLS    AND PORT IN ('GT','LA','LF','NY','PR','PT','SA')
       IIF(PS_ACCOUNT_NUMBER_V = '112320','ACCOUNT/REGION/PORT',                           --TMS    AND PORT IN ('GT','LA','LF','NY','PT','SA')
       IIF(PS_ACCOUNT_NUMBER_V = '210220','ACCOUNT/REGION/PORT',                           --TMS    AND PORT IN ('JX')
       IIF(PS_ACCOUNT_NUMBER_V = '210260','ACCOUNT/REGION/PORT',                           --TMS    AND PORT IN ('SF','WS')
       IIF(PS_ACCOUNT_NUMBER_V = '460040','ACCOUNT/REGION/PORT',                           --TLS    AND PORT IN ('GT','LA','LF','NY','PT','SA')
       IIF(PS_ACCOUNT_NUMBER_V = '500000','ACCOUNT/REGION/PORT/PRODUCT',                   --TMS    AND PORT IN ('GT','JX','NY','PT','SA')
       IIF(PS_ACCOUNT_NUMBER_V = '513000','ACCOUNT/REGION/PORT',                           --TMS    AND PORT IN ('JX','LA','LF','NY','SF','WS')
	   IIF(PS_ACCOUNT_NUMBER_V = '602045','ACCOUNT/REGION/PORT')))))))),                   --TMS    AND PORT IN ('LA','NY','PR','PT','NY')
IIF(INSTR(TRANSACTION_TYPE_NAME_V,'RP2')!=0,
       IIF(PS_ACCOUNT_NUMBER_V = '112300','ACCOUNT/REGION/PORT',                           --TLS    AND PORT IN ('GT','LA','NY','PT','SA')
       IIF(PS_ACCOUNT_NUMBER_V = '112320','ACCOUNT/REGION/PORT',                           --TMS    AND PORT IN ('GT','LA','NY','PT','SA')
       IIF(PS_ACCOUNT_NUMBER_V = '210260','ACCOUNT/REGION/PORT',                           --TMS    AND PORT IN ('BC','CM','WS')
       IIF(PS_ACCOUNT_NUMBER_V = '460040','ACCOUNT/REGION/PORT',                           --TLS    AND PORT IN ('GT','PR','LA','NY','PT','SA')
       IIF(PS_ACCOUNT_NUMBER_V = '500000','ACCOUNT/REGION/PORT/PRODUCT',                   --TMS    AND PORT IN ('BC','CM','GT','LA','NY','PT','SA')
       IIF(PS_ACCOUNT_NUMBER_V = '513000','ACCOUNT/REGION/PORT',                           --TMS    AND PORT IN ('BC','WS','LA','NY')
	   IIF(PS_ACCOUNT_NUMBER_V = '602045','ACCOUNT/REGION/PORT'))))))),	                   --TMS    AND PORT ALL
IIF(INSTR(TRANSACTION_TYPE_NAME_V,'TR1')!=0,
       IIF(PS_ACCOUNT_NUMBER_V = '112300','ACCOUNT/REGION/PORT',                           --TLS    AND PORT IN ('GT','LA','LF','NY')
       IIF(PS_ACCOUNT_NUMBER_V = '112320','ACCOUNT/REGION/PORT',                           --TMS    AND PORT IN ('LA','LF')
       IIF(PS_ACCOUNT_NUMBER_V = '210260','ACCOUNT/REGION/PORT',                           --TMS    AND PORT IN ('BC')
       IIF(PS_ACCOUNT_NUMBER_V = '220385','ACCOUNT/REGION/PORT',                           --TMS    AND PORT IN ('LA')
       IIF(PS_ACCOUNT_NUMBER_V = '460040','ACCOUNT/REGION/PORT',                           --TLS    AND PORT IN ('LA','LF')
       IIF(PS_ACCOUNT_NUMBER_V = '500000','ACCOUNT/REGION/PORT/PRODUCT',                   --TMS    AND PORT IN ('BC','LA','LF')
       IIF(PS_ACCOUNT_NUMBER_V = '513000','ACCOUNT/REGION/PORT',                           --TMS    AND PORT IN ('LF')
	   IIF(PS_ACCOUNT_NUMBER_V = '602045','ACCOUNT/REGION/PORT')))))))),                   --SUSP   AND PORT ALL
IIF(INSTR(TRANSACTION_TYPE_NAME_V,'RON')!=0,
       IIF(PS_ACCOUNT_NUMBER_V = '112300','ACCOUNT/REGION/PORT',                           --TLS    AND PORT IN ('GT','LA','LF','NY','PR','PT','SA','TP')
       IIF(PS_ACCOUNT_NUMBER_V = '112320','ACCOUNT/REGION/PORT',                           --TMS    AND PORT IN ('GT','LA','LF','NY','PR','PT','SA','TP')
       IIF(PS_ACCOUNT_NUMBER_V = '210220','ACCOUNT/REGION/PORT',                           --TMS    AND PORT IN ('JX')
       IIF(PS_ACCOUNT_NUMBER_V = '210260','ACCOUNT/REGION/PORT',                           --TMS    AND PORT IN ('BC','CM','WS')
       IIF(PS_ACCOUNT_NUMBER_V = '460070','ACCOUNT/REGION/PORT',                           --TLS    AND PORT IN ('GT','LA','LF','PR','PT','SA','TP')
       IIF(PS_ACCOUNT_NUMBER_V = '510020','ACCOUNT/REGION/PORT',                           --TMS    AND PORT IN ('BC','CM','GT','JX','LA','LF','PR','PT','SA','TP','WS')
       IIF(PS_ACCOUNT_NUMBER_V = '513000','ACCOUNT/REGION/PORT',                           --TMS    AND PORT IN ('NY')
	   IIF(PS_ACCOUNT_NUMBER_V = '602045','ACCOUNT/REGION/PORT')))))))),                   --SUSP   AND PORT ALL                   
IIF(INSTR(TRANSACTION_TYPE_NAME_V,'ROF')!=0,
       IIF(PS_ACCOUNT_NUMBER_V = '112300','ACCOUNT/REGION/PORT',                           --TLS    AND PORT IN ('GT','NY')
       IIF(PS_ACCOUNT_NUMBER_V = '112320','ACCOUNT/REGION/PORT',                           --TMS    AND PORT IN ('GT','NY')
       IIF(PS_ACCOUNT_NUMBER_V = '210260','ACCOUNT/REGION/PORT',                           --TMS    AND PORT IN ('BC')
       IIF(PS_ACCOUNT_NUMBER_V = '460040','ACCOUNT/REGION/PORT',                           --TLS    AND PORT IN ('NY')
       IIF(PS_ACCOUNT_NUMBER_V = '510020','ACCOUNT/REGION/PORT',                           --TMS    AND PORT IN ('BC','GT','NY')
       IIF(PS_ACCOUNT_NUMBER_V = '513000','ACCOUNT/REGION/PORT',                           --TMS    AND PORT IN ('NY')
	   IIF(PS_ACCOUNT_NUMBER_V = '602045','ACCOUNT/REGION/PORT'))))))),                    --TMS    AND PORT IN ('NY')
NULL))))))))))))))))))))))))))))))))))